import io
import datetime
from weasyprint import HTML, CSS


def generate_report_pdf(scan_data: dict, findings: list) -> io.BytesIO:
    # 1. Format date
    try:
        dt = datetime.datetime.fromisoformat(
            str(scan_data.get("created_at")).replace("Z", "+00:00")
        )
        date_str = dt.strftime("%B %d, %Y")
    except Exception:
        date_str = "Unknown Date"

    # 2. Determine score label and color
    score = scan_data.get("score", 0)
    if score < 50:
        score_label = "CRITICAL"
        score_color = "#ff4444"
    elif score < 80:
        score_label = "AT RISK"
        score_color = "#f5a623"
    else:
        score_label = "SECURE"
        score_color = "#50e3c2"

    url = scan_data.get("target_url", "Unknown URL")

    # 3. HTML Template
    # We use a pure black and white minimalist style matching the Vercel aesthetic
    html_content = f"""
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Security Audit Report</title>
        <style>
            @page {{
                size: A4;
                margin: 20mm 20mm 30mm 20mm;
                @bottom-left {{
                    content: "Generated by LYNCE · lynce.io";
                    font-family: system-ui, -apple-system, sans-serif;
                    font-size: 8pt;
                    color: #888888;
                }}
                @bottom-right {{
                    content: counter(page);
                    font-family: ui-monospace, monospace;
                    font-size: 8pt;
                    color: #888888;
                }}
            }}
            
            body {{
                font-family: system-ui, -apple-system, sans-serif;
                color: #000000;
                line-height: 1.6;
                margin: 0;
                padding: 0;
            }}

            .monospace {{
                font-family: ui-monospace, monospace;
            }}

            /* Header */
            .header {{
                margin-bottom: 2rem;
            }}
            .header h1 {{
                font-size: 28pt;
                font-weight: 700;
                margin: 0;
                letter-spacing: -0.04em;
            }}
            .header h2 {{
                font-size: 14pt;
                font-weight: 400;
                color: #666666;
                margin: 0;
                margin-top: 4px;
            }}
            .divider {{
                border-top: 1px solid #eaeaea;
                margin: 2rem 0;
            }}

            /* Summary */
            .summary {{
                display: flex;
                flex-direction: column;
                margin-bottom: 3rem;
            }}
            .summary-item {{
                font-size: 11pt;
                margin-bottom: 8px;
            }}
            .summary-label {{
                color: #666666;
                display: inline-block;
                width: 120px;
                font-weight: 500;
            }}
            .score-container {{
                margin-top: 2rem;
            }}
            .score-value {{
                font-size: 48pt;
                font-weight: bold;
                letter-spacing: -0.04em;
                line-height: 1;
            }}
            .score-label {{
                font-size: 14pt;
                font-weight: 600;
                letter-spacing: 0.1em;
            }}

            /* Findings */
            .finding {{
                margin-bottom: 2.5rem;
                page-break-inside: avoid;
            }}
            .finding-header {{
                margin-bottom: 0.5rem;
            }}
            .finding-category {{
                font-size: 14pt;
                font-weight: 600;
                text-transform: uppercase;
                letter-spacing: 0.05em;
                margin-bottom: 0.2rem;
            }}
            .finding-meta {{
                font-size: 10pt;
                margin-bottom: 1rem;
            }}
            .badge {{
                display: inline-block;
                border: 1px solid #000;
                padding: 2px 8px;
                border-radius: 9999px;
                font-size: 8pt;
                font-weight: 600;
                text-transform: uppercase;
                margin-right: 12px;
            }}
            .badge.critical, .badge.high {{ color: #ff4444; border-color: #ff4444; }}
            .badge.medium {{ color: #f5a623; border-color: #f5a623; }}
            .badge.low, .badge.pass {{ color: #50e3c2; border-color: #50e3c2; }}
            
            .finding-desc {{
                font-size: 11pt;
                color: #333333;
                margin-bottom: 1rem;
            }}
            .finding-rec {{
                margin-left: 1.5rem;
                padding-left: 1rem;
                border-left: 2px solid #eaeaea;
                color: #666666;
            }}
            .finding-rec-label {{
                font-size: 8pt;
                font-weight: 600;
                text-transform: uppercase;
                letter-spacing: 0.1em;
                margin-bottom: 4px;
            }}
            .finding-rec-text {{
                font-size: 10pt;
            }}
            .finding-divider {{
                border-top: 1px solid #eaeaea;
                margin-top: 2rem;
            }}
        </style>
    </head>
    <body>
        <div class="header">
            <h1>LYNCE</h1>
            <h2>Security Audit Report</h2>
        </div>
        <div class="divider"></div>
        
        <div class="summary">
            <div class="summary-item"><span class="summary-label">Target URL:</span> <span class="monospace">{url}</span></div>
            <div class="summary-item"><span class="summary-label">Date Scanned:</span> <span>{date_str}</span></div>
            
            <div class="score-container">
                <div class="score-value monospace" style="color: {score_color};">{score}</div>
                <div class="score-label" style="color: {score_color};">{score_label}</div>
            </div>
        </div>
        
        <div class="divider"></div>
        
        <div class="findings-list">
    """

    for fd in findings:
        cat = fd.get("category", "Unknown")
        sev = fd.get("severity", "medium").lower()
        title = fd.get("title", "")
        desc = fd.get("description", "")
        rec = fd.get("recommendation", "")

        status_symbol = (
            "✓ PASS"
            if sev == "pass"
            else ("⚠ WARNING" if sev in ["warning", "medium", "low"] else "✗ FAIL")
        )

        # Build HTML for this finding
        html_content += f"""
        <div class="finding">
            <div class="finding-header">
                <div class="finding-category">{cat}</div>
                <div class="finding-meta">
                    <span class="badge {sev}">{sev}</span>
                    <strong>{status_symbol}</strong> &middot; {title}
                </div>
            </div>
            <div class="finding-desc">{desc}</div>
        """

        if rec:
            html_content += f"""
            <div class="finding-rec">
                <div class="finding-rec-label">Recommendation</div>
                <div class="finding-rec-text">{rec}</div>
            </div>
            """

        html_content += """
            <div class="finding-divider"></div>
        </div>
        """

    if not findings:
        html_content += """
        <div style="text-align: center; margin-top: 4rem;">
            <div style="font-size: 14pt; font-weight: 600;">Perfect Security</div>
            <div style="color: #666;">No security findings were detected during the scan.</div>
        </div>
        """

    html_content += """
        </div>
    </body>
    </html>
    """

    pdf_buffer = io.BytesIO()
    HTML(string=html_content).write_pdf(target=pdf_buffer)
    pdf_buffer.seek(0)

    return pdf_buffer
